// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4PRW_csN9zVtlQFT9bDM2SUyadg-j-w',
    appId: '1:1017041920307:web:1a50831e6bc1d75c071e46',
    messagingSenderId: '1017041920307',
    projectId: 'apptwig-9f53a',
    authDomain: 'apptwig-9f53a.firebaseapp.com',
    storageBucket: 'apptwig-9f53a.appspot.com',
    measurementId: 'G-T52W8J1W4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqq9G0IA-dd98HZVsOtm1xbYqNXlfkCI',
    appId: '1:1017041920307:android:338a6b7312d8c8c4071e46',
    messagingSenderId: '1017041920307',
    projectId: 'apptwig-9f53a',
    storageBucket: 'apptwig-9f53a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX5GJjoKuu4MnP9y6Tvwm4phGWfdrTHzo',
    appId: '1:1017041920307:ios:a9464ee9d9b69531071e46',
    messagingSenderId: '1017041920307',
    projectId: 'apptwig-9f53a',
    storageBucket: 'apptwig-9f53a.appspot.com',
    androidClientId: '1017041920307-p3g08pa04vioo1e454rp4cl2scetdut1.apps.googleusercontent.com',
    iosClientId: '1017041920307-42mko4g100c2jn7imslg7b1b98nmsooq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX5GJjoKuu4MnP9y6Tvwm4phGWfdrTHzo',
    appId: '1:1017041920307:ios:a9464ee9d9b69531071e46',
    messagingSenderId: '1017041920307',
    projectId: 'apptwig-9f53a',
    storageBucket: 'apptwig-9f53a.appspot.com',
    androidClientId: '1017041920307-p3g08pa04vioo1e454rp4cl2scetdut1.apps.googleusercontent.com',
    iosClientId: '1017041920307-42mko4g100c2jn7imslg7b1b98nmsooq.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
